[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/jobs/*"
  to = "/db.json"
  status = 200

[[redirects]]
  from = "/api/jobs"
  to = "/db.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 